name: bolanet76
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  dio: ^5.7.0
  webview_flutter: ^4.8.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  get_storage: ^2.1.1
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  just_audio: ^0.9.42
  youtube_player_flutter: ^9.1.1
  audioplayers: ^6.1.0
  firebase_database: 11.1.6
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  shared_preferences: ^2.3.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 
    
